[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.69"
thiserror = "1.0.60"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["Window", "Document", "HtmlElement", "Node", "console"] }

[lib]
crate-type = ["cdylib", "rlib"]
